services:
  - type: web
    name: tienda-backend
    runtime: python
    plan: free

    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        sync: false

      - key: ALLOWED_HOSTS
        value: "https://tienda-backend-2g3c.onrender.com"

      - key: FRONTEND_URL
        value: "http://localhost:4200"

      - key: MP_ACCESS_TOKEN
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_KEY
        sync: false
