# Generated by Django 5.2.6 on 2025-11-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok'), ('Converse', 'Converse'), ('Vans', 'Vans'), ('New Balance', 'New Balance'), ('Asics', 'Asics'), ('Under Armour', 'Under Armour'), ('Otra', 'Otra')], default='Otra', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], default='40', max_length=10),
        ),
    ]
