# Generated by Django 5.2.6 on 2025-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_marca_producto_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('fallido', 'Pago fallido')], default='pendiente', max_length=20)),
                ('wompi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
