# Generated by Django 5.2.6 on 2026-04-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('comprado', 'Comprado'), ('enviado', 'Enviado'), ('en_reparto', 'En reparto'), ('entregado', 'Entregado')], default='comprado', max_length=20),
        ),
    ]
