# Generated by Django 5.2.6 on 2026-05-04 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(blank=True, max_length=255)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('in_process', 'En proceso')], default='pending', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_mp', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Pago Mercado Pago',
                'verbose_name_plural': 'Pagos Mercado Pago',
                'db_table': 'tienda_pago_mercadopago',
            },
        ),
    ]
