# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_pagomercadopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
