# Generated by Django 5.2.6 on 2026-06-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprado', 'Comprado'), ('enviado', 'Enviado'), ('en_reparto', 'En reparto'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
