from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_pedido_referencia_pago'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "tienda_pago_mercadopago" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "preference_id" varchar(255) NOT NULL,
                "payment_id" varchar(255) NOT NULL,
                "estado" varchar(50) NOT NULL,
                "monto" numeric(10, 2) NOT NULL,
                "creado" timestamp with time zone NOT NULL,
                "actualizado" timestamp with time zone NOT NULL,
                "pedido_id" bigint NOT NULL UNIQUE REFERENCES "tienda_pedido"("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql='DROP TABLE IF EXISTS "tienda_pago_mercadopago"',
        ),
    ]
